1. Fixed error: java.lang.NoSuchMethodError: com.amazonaws.services.cloudwatch.AmazonCloudWatch.putMetricData; (#1)
2. Fixed compilation error caused by obsolete dependencies in aws java sdk by using more recent dependencies;
3. Added items from IDEA to .gitignore file.